### ISSUE TITLE
Broken blog link

### ISSUE THREAD

**Issue by NicoHood** [nims11/IPod-Shuffle-4g#12]
I just want to mention that http://shuffle3db.wikispaces.com/iTunesSD3gen is now offline. If you find the same information someone else and update would be nice.

**Comment by nims11** [comment]
Blog updated as well

**Comment by NicoHood** [comment]
I just found out that you used the wayback machine to get this data. I would not rely on this and locally copy this information into a `/docs` folder inside this repository. Probably in markdown formattet. It would be a pity to lose this information.
