### ISSUE TITLE
Broken (.pls) playlist track paths gives error

### ISSUE THREAD

**Issue by NicoHood** [nims11/IPod-Shuffle-4g#16]
```
Traceback (most recent call last):
  File "./shuffle.py", line 576, in <module>
    shuffle.write_database()
  File "./shuffle.py", line 512, in write_database
    f.write(self.tunessd.construct())
  File "./shuffle.py", line 212, in construct
    play_header = self.play_header.construct(self.track_header.tracks)
  File "./shuffle.py", line 350, in construct
    construction = playlist.construct(tracks)
  File "./shuffle.py", line 451, in construct
    position = tracks.index(self.ipod_to_path(i))

ValueError: "/media/linuxuser/NICO'S IPOD/music/k.i.z./ganz oben/01 - duhastaufdeinenkokaturndeinegeistigbehinderteschwestergefiktmucke.mp3" is not in list
```

I used this within a playlist, that gave me the error. Not using playlists is file. I guess its just a too long name (or path!!) of the song. And yeah, that is an official name. K.I.Z. fucked you again ;D

**Comment by nims11** [comment]
I am unable to reproduce this error with m3u playlist. Try debugging by printing the content of `tracks` and `self.ipod_to_path(i)`. Use `repr` to print to notice any character level discrepancies.

**Comment by NicoHood** [comment]
```
ValueError: "/NICO'S IPOD/ipod_control/music/k.i.z./hahnenkampf (re-release)/01 - geld essen (ausgestopfte rapper).mp3" is not in list

IPod-Shuffle-4g$ ls /NICO\'S\ IPOD/ipod_control/music/k.i.z./hahnenkampf\ \(re-release\)/
01 - Geld Essen (Ausgestopfte Rapper).mp3


File1=iPod_Control/Music/K.I.Z./Hahnenkampf (Re-Release)/01 - Geld Essen (Ausgestopfte Rapper).mp3
Title1=Geld Essen (Ausgestopfte Rapper)
```

Might be related with https://github.com/nims11/IPod-Shuffle-4g/issues/4

**Comment by NicoHood** [comment]
I printed the `position` value in the place where the code crashes, and the name of the file as well.
First the scripts adds the master playlist and seems to find the correct index (24). But when adding the .pls file it does not work anymore.

Debug output for adding master playlist:
```
/media/linuxuser/NICO'S IPOD/ipod_control/music/k.i.z/hahnenkampf (re-release)/01 - geld essen (ausgestopfte rapper).mp3
kkkkk
24

# adding the K.I.Z. playlist
/media/linuxuser/NICO'S IPOD/ipod_control/music/k.i.z./hahnenkampf (re-release)/01 - geld essen (ausgestopfte rapper).mp3
kkkkk
#then the error occurs
# but its sais it has this entry:
/media/linuxuser/NICO'S IPOD/ipod_control/music/k.i.z/hahnenkampf (re-release)/01 - geld essen (ausgestopfte rapper).mp3
```

Not sure why it does work for the master playlist but not for the .pls file.

**Comment by NicoHood** [comment]
Debugging this line a bit further gives us more hints:
https://github.com/nims11/IPod-Shuffle-4g/blob/e02ef0fff658990238625c10bb0150be4d60e3a0/shuffle.py#L447-L449

```
/media/linuxuser/NICO'S IPOD/ipod_control/music/k.i.z./hahnenkampf (re-release)/01 - geld essen (ausgestopfte rapper).mp3
/media/linuxuser/NICO'S IPOD/ipod_control/music/k.i.z/hahnenkampf (re-release)/01 - geld essen (ausgestopfte rapper).mp3
```

`self.ipod_to_path(i)` has got the last dot of `K.I.Z.` and `tracks` only got `K.I.Z`

I dont know why its missing, but i will follow this error.

**Comment by NicoHood** [comment]
Fix/workaround:
https://github.com/NicoHood/IPod-Shuffle-4g/commit/92d121330c1ed29cbe959343d0e793df9480fae2

Explanation:
https://github.com/NicoHood/IPod-Shuffle-4g/commit/f313664a97c09c43d5c873580c30deaaed3bf110

So it is an upstream bug of rhythmbox. We should report it. I am using 3.3 which is the latest version.

**Comment by NicoHood** [comment]
v1.2 also fixes this.
