### ISSUE TITLE
Add releases + changelog

### ISSUE THREAD

**Issue by NicoHood** [nims11/IPod-Shuffle-4g#20]
Since we fixed some issues and are going to fix a lot more, it would make sense to keep track of it.

I suggest to start from v1.0 (the original code you forked) and add a list of the fixes you made so far. After that you can tag new releases here:
https://github.com/nims11/IPod-Shuffle-4g/releases

Btw thx for looking into the othe issues I opened. I am currently trying to fix this disabled voiceover thing. Also I sent you an email some time ago, you must have missed it?

**Comment by NicoHood** [comment]
Oh and maybe we should inform the original autor of the existence of this fork? So he can possibly link to this one. However google finds your post first anyways.

**Comment by nims11** [comment]
b471e1c7
