### ISSUE TITLE
Voiceover per playlists and tracks

### ISSUE THREAD

**Issue by NicoHood** [nims11/IPod-Shuffle-4g#26]
I'd like to discuss the voiceover feature:
If you ask me I prefer to disable it by default. This also makes the script independent from any voiceover dependencies. Voiceover just uses more storage capacity of the limited 2gb. So why not disable it by default?

And the 2nd point is: We could enable voiceover for tracks and playlists separately. This gives us a lot advantages:
* Only use playlist voiceover to find the correct playlist out of the 1000 playlists we have, but save memory for tracks
* Only enable it for tracks to only use it if you need to. Playlists dont use the "ugly" voice. (How Itunes does it)
* Use both cause you want to have voiceover an everything

So we need to add those features:
* Switch disable to enable
* New parameter names (enable voiceover for tracks/playlists)
* Separate between tracks and playlists implementation

**Comment by NicoHood** [comment]
@nims11 @mmalisz I currently think of using "All Songs" by the built in ipod voice every time, no matter if you use voiceover to generate the other playlist names properly. What do you think of this? As i find the generated voices very unclear but still better than just a number I'd at least keep the master clean so you always find this very fast.

**Comment by NicoHood** [comment]
Fixed by #29 
Please give feedback about the question above.

**Comment by mmalisz** [comment]
The build in voice is more clear indeed.
However, some might find confusing hearing two different voices.
As for me either will work.

**Comment by nims11** [comment]
Fine either way for me. Shouldn't bother anyone.
