### ISSUE TITLE
[Request] Convert FLAC to alac (m4a)

### ISSUE THREAD

**Issue by mmalisz** [nims11/IPod-Shuffle-4g#28]
It would be a nice feature to automaticly convert flac to m4a (or any other lossless ipod compatible format).
I've got a lots of flac albums which I had encoded a while ago and I don't really want to encode them all once again.

**Comment by NicoHood** [comment]
Duplicate of #11

**Comment by mmalisz** [comment]
If I've understood correctly, you want to compress the files to use less space.
What I want is to convert flac files (which are not supported by ipod) to any other supported format (alac, wav) with keeping the quality.

As I intended, the files with unsupported codec would be converted automaticly to the desired format 'on the fly', overwriting / removing original files.

**Comment by NicoHood** [comment]
What me and you want can be merged.
A simple script that imports music onto your ipod and can convert them to any specific format and optionally add compression (as the shuffle only has 2gb).

As I said a simple bash script would be best and also this does not have to be integrated into the shuffle.py file (as it has nothing to do with the database generation). So feel free to write a bash script. I'd also write a bash script. And btw: I do not know much bash and python neither. When I modified this script I had not a single plan about python (and i am still far away from pro) ;)

**Comment by mmalisz** [comment]
For the keeping it clean sake, I close it.
In case of any further ideas / results, will post them at #11.

**Comment by nims11** [comment]
shuffle.py should only be creating ipod db IMO. As discussed in #11 , an additional import helper script should be a place where we should stuff in features like compression and transcoding.
