### ISSUE TITLE
Switch to python3

### ISSUE THREAD

**Issue by NicoHood** [nims11/IPod-Shuffle-4g#32]
`2to3 -w filename.py` can be used to autoconvert the script. However this gives a few errors, as not all is translated correct.

Edit: it took some time but I think i managed to get the code working. I have not tested all options yet though. Please test release 1.5

**Comment by nims11** [comment]
Completely dropping python2 support won't be wise when python2 is still in active use. Most projects support both python2 and python3 simultaneously. (py2 will stay till 2020).
Some relevant references:
https://docs.python.org/3/howto/pyporting.html
https://pythonhosted.org/six/

**Comment by NicoHood** [comment]
Can't we somehow make it compatible for both versions? However I think that 1.4 has tons of new features/fixes which can be used for python2 only people. And which system today has no python3 available? I think thats is less critical. python2 is legacy and so is 1.4 legacy i'd say.
