### ISSUE TITLE
UnicodeEncodeError when playlist name has non ascii characters

### ISSUE THREAD

**Issue by nims11** [nims11/IPod-Shuffle-4g#35]

**Comment by NicoHood** [comment]
Is this still required in python3? This gives me a merge conflict now:
```python
        # Handle the VoiceOverData
<<<<<<< HEAD
        self["dbid"] = hashlib.md5(text.encode('utf-8')).digest()[:8]
=======
        if isinstance(text, unicode):
            text = text.encode('utf-8', 'ignore')
        self["dbid"] = hashlib.md5(text).digest()[:8] #pylint: disable-msg=E1101
>>>>>>> upstream/master
        self.text_to_speech(text, self["dbid"], True)
```
Since python3 changes some unicode stuff I do not know if its still required. How would you reproduce such a bug?

**Comment by nims11** [comment]
You can override the conflict with your own version in python3 since py3 `hashlib.md5` takes byte string as argument and every string is unicode by default.
