### ISSUE TITLE
GPG signatures for source validation

### ISSUE THREAD

**Issue by NicoHood** [nims11/IPod-Shuffle-4g#39]
As we all know, today more than ever before, it is crucial to be able to trust our computing environments. One of the main difficulties that package maintainers of Linux distributions face, is the difficulty to verify the authenticity and the integrity of the source code.

The Arch Linux team would appreciate it if you would provide us GPG signatures in order to verify easily and quickly of your source code releases.

**Overview of the required tasks:**
* [x] Please [create and/or use a 4096-bit RSA keypair](https://wiki.archlinux.org/index.php/GnuPG#Create_key_pair) for the file signing
* The key may be used for [email encryption](https://www.enigmail.net/index.php/en/) too
* Keep your key secret, use a strong unique passphrase for the key
* [x] Upload the public key to a key server
* [x] [Sign every new commit by default](https://help.github.com/articles/signing-commits-using-gpg/)
* [ ] [Sign new tags](https://help.github.com/articles/signing-tags-using-gpg/)
* Verify the Github Release tarball download against your local source
* [x] [Sign Github Release tarballs](https://wiki.debian.org/Creating%20signed%20GitHub%20releases)

**Additional Information:**
* https://help.github.com/categories/gpg/
* https://git-scm.com/book/en/v2/Git-Tools-Signing-Your-Work
* https://www.qubes-os.org/doc/verifying-signatures/
* https://developers.google.com/web/fundamentals/security/encrypt-in-transit/why-https

Thanks.

**Comment by NicoHood** [comment]
Should I sign the release instead?

**Comment by nims11** [comment]
Didn't know had to sign the previous releases. Can you check if it is fine? (am a noob with gpg stuff but have started using it thanks to you)

**Comment by NicoHood** [comment]
How is your fingerprint? I need the full fingerprint of your key. I will then update the AUR package and tell you if its good or not.

**Comment by NicoHood** [comment]
ipod-shuffle-4g-1.4.tar.gz ... Passed (WARNING: the key has expired.)

How did you generate your key? You need to increase the expire date.

**Comment by nims11** [comment]
My key had expired few months ago and I had renewed it, but hadn't uploaded to the public keyserver or my website. Can you verify now?

**Comment by NicoHood** [comment]
Thanks, working now!

**Comment by NicoHood** [comment]
Hey nims, your GPG key C838FC13F0FD455541C590412B6DAF67FFAE3F83 expired already in 2019. Could you please renew the expire date and upload it to the keyservers?

https://unix.stackexchange.com/questions/177291/how-to-renew-an-expired-keypair-with-gpg

**Comment by nims11** [comment]
Hey, sorry I was using a renewed key since a while and hadn't uploaded it yet to my website and keyservers. Done now.
