### ISSUE TITLE
Doesn't import artists with a hyphen in the name.

### ISSUE THREAD

**Issue by ioreshnikov** [nims11/IPod-Shuffle-4g#4]
Hello.

I've noticed that shuffle.py doesn't import tracks for the artists with a unicode U+2010 hyphen in their name, like in "Wu-Tang Clan" for example.

Best regards.

**Comment by ioreshnikov** [comment]
Hello.

I've managed to pinpoint the issue a little bit further. I import the music with Rhythmbox's MTP plugin using playlists for convinient voiceover navigation. This results in unicode paths which the script seems to be unable to handle correctly even when using --rename-unicode option. Renaming directory names and paths inside playlists solves the importing problem.

Best regards.

**Comment by ioreshnikov** [comment]
Sorry, closed the issue by mistake.

**Comment by nims11** [comment]
Thanks for reporting. I remember facing this problem specifically with Rhythmbox's MTP plugin. It sometimes produces the wrong playlist files (I later switched to clementine, with no such issues). Let me take a look at it again.

**Comment by NicoHood** [comment]
Does the new 1.2 version give you an error message at least?

**Comment by NicoHood** [comment]
Adding `test'.mp3` gives the error. I fixed it here:
https://github.com/NicoHood/IPod-Shuffle-4g/tree/autoplaylist

(commit will be edited, github doesnt update at the moment)

**Comment by NicoHood** [comment]
Please close this issue @nims11 , fixed in #29

**Comment by nims11** [comment]
Wasn't able to reproduce with `test'.mp3`. Any specific point you want to mention here?

**Comment by NicoHood** [comment]
I got a mutagen crash with this filename. My fix just avoids a crash and reports an error. We cannot really fix this issue though.
