### ISSUE TITLE
it's not generating an index

### ISSUE THREAD

**Issue by cryptopsy1** [nims11/IPod-Shuffle-4g#43]
My procedure:
-remove all the files from the shuffle
-boot in windows so it regenerates the control folder
-boot in linux and copy a folder to the mount point of the ipod, then run the script
```
# /root/.p/ipod-shuffle-4g/2016q4/ipod-shuffle-4g.py . 
# the pwd is the mount point where the control folder is and where my music folder is placed as well

drwxr-xr-x 2 root root 16K Jan  1  2016 dos-ep
drwxr-xr-x 6 root root 16K Mar 22 14:06 iPod_Control
```
the output is:
Database written successfully:
Tracks 0
Albums 0
Artists 0
Playlists 0

**Comment by NicoHood** [comment]
can you please `ls` this directory? Does it even has music files inside?
Also try `--verbose` to the script.

**Comment by cryptopsy1** [comment]
i bought a new shuffle and it still doesn't work. It worked with my old shuffle a long time ago. 

|-- [ 16K]  .Trashes
|-- [4.0K]  ._.Trashes
|-- [ 16K]  iPod_Control
|   |-- [ 16K]  Music
|   |-- [ 16K]  Speakable
|   |   |-- [ 16K]  Playlists
|   |   `-- [ 16K]  Tracks
|   `-- [ 16K]  iTunes
|       `-- [ 200]  iTunesSD
`-- [ 16K]  novadriver
    |-- [ 16K]  deeper-high
    |   |-- [ 11M]  01-you_want_yours,_you_want_mine.mp3
    |   |-- [6.3M]  02-roll_you.mp3
    |   |-- [8.3M]  03-deeper_high.mp3
    |   |-- [7.7M]  04-turn_to_stone.mp3
    |   |-- [ 11M]  05-dark_aftermath.mp3
    |   |-- [7.9M]  06-machine.mp3
    |   |-- [8.4M]  07-bury_me_alive.mp3
    |   |-- [6.4M]  08-stars_after_stars.mp3
    |   |-- [9.1M]  09-push_the_river.mp3
    |   |-- [ 13M]  10-blackout.mp3
    |   `-- [8.7M]  11-whiteout.mp3
shuffle.py: error: unrecognized arguments: --verbose

**Comment by cryptopsy1** [comment]
when i unmount and press the play button, there is an audio clip saying  "'please use itunes to sync music to this ipod'. my command was "shuffle.py . --disable-voiceover"

**Comment by cryptopsy1** [comment]
when i unmount and press the play button, there is an audio clip saying  "'please use itunes to sync music to this ipod'. my command was "shuffle.py . --disable-voiceover"

**Comment by NicoHood** [comment]
@cryptopsy1 Please use the latest version of the script. It seems you are using an older version if verbose is not available. Please show us the `--help` output.

**Comment by NicoHood** [comment]
If this is still an issue, leave a comment please.
