### ISSUE TITLE
review of ipod-shuffle-4g

### ISSUE THREAD

**Issue by wsdookadr** [nims11/IPod-Shuffle-4g#46]
I mounted the device, copied the music over in mp3 format, ran **ipod-shuffle-4g.py** on the mounted directory, unmounted the device. Now I can listen to all the songs, no complications, no GUIs.
Thank you so much! It was about time, I hated Apple's iTunes, that slow bloated piece of f***ing s***.

**Comment by NicoHood** [comment]
Thanks! :)
