### ISSUE TITLE
Cannot sync

### ISSUE THREAD

**Issue by mmalisz** [nims11/IPod-Shuffle-4g#5]
I've recently switch to another machine with Debian 8.0. Previously I ran Debian 7.X and everything was fine.
Now, I get an error:
http://pastebin.com/raw.php?i=EFzYR47x
When there are no files, IPOD sync withour error.

**Comment by mmalisz** [comment]
I just found out what's wrong.
Either mutagen or the script itself changes ecery name (even dirs) to lowercase.

**Comment by nims11** [comment]
It is the script which changes file paths to lowercase. Since the ipod file system is fat32, case shouldn't have causes any issue. Let me take a look on what I can do so that the script preserves the case.

**Comment by mmalisz** [comment]
Any news on the issue?

**Comment by NicoHood** [comment]
I want to add a little information to this issue:
The Rythmbox plugin keeps upper/lower case. It also does not use the `stop_at_pos_ms` attribute and leaves it zero instead.

**Comment by NicoHood** [comment]
@mmalisz can you please try again with v1.2 and provide further information?

**Comment by mmalisz** [comment]
@NicoHood, here you are:
http://pastebin.com/raw/nSPUnCkJ

**Comment by mmalisz** [comment]
The full path is:
/media/mihau/IPOD/iPod_Control/Music/F00/ARZF.m4a

**Comment by NicoHood** [comment]
Thanks. Can you please do `ls -la /media/mihau/IPOD/ipod_control/music/f00/`

**Comment by mmalisz** [comment]
@NicoHood, sorry, I don't get email notifications. I'll post it to you as soon I'll be home.

**Comment by mmalisz** [comment]
@NicoHood, I totaly forgot. Here you are:
http://pastebin.com/raw/S16Wyn99
These are all folders within Music directory.
The iPod's been synched with iTunes on Windows.

**Comment by NicoHood** [comment]
I need an ls on the file that outputs the error of course.
`Adding track /media/mihau/IPOD/va/fokuz_podcast_20_-_macca_and_kasper.mp3`

So the `va` directory is interesting. 
You can also try to rename the file into a normal word like `testname` and see if this solved the problem.

**Comment by mmalisz** [comment]
I cannot provide this path as I formatted my iPod under Windows.
Anyway, 'va' folder was actually 'VA", and if you download the podcast from [https://soundcloud.com/fokuzrecordings/fokuz-recordings-podcast-20-macca-kasper](here) you'll see that mp3 file also contains uppercase characters.
So, basically, the script has an issue with case-sesnivity.

**Comment by mmalisz** [comment]
As of the file of error, the other ls produces the error as well.
Compare included paste and result of the ls from previous posts.

**Comment by NicoHood** [comment]
I added the file `Fokuz Recordings Podcast #20 - Macca & Kasper by Fokuz Recor.mp3` (no matter which content) into my ipods root directory and the script works fine.

Are you still able to reproduce this?
If yes, please provide the full filename of this file (via ls) and try to rename it to something simple.

**Comment by NicoHood** [comment]
As the very first post shows this is a mutagen error. This should be fixed and related with #4 
Please test the fix provided there and close the issue if possible.
You might still get an error, but no python crash.

**Comment by mmalisz** [comment]
So, here's the log:
http://pastebin.com/ApXqN4vx
Here's the result of doing ls within iPod_Control/Music/ dir where are files synced via itunes on windows and VA dir, where I've put 2 new files and a playlist:
http://pastebin.com/ED0gAJuj

As you can see, the script doesn't respect uppercases (changes all the names, even directories to lowercase). That's what I've reported from the very beginning.

**Comment by mmalisz** [comment]
If you compare the very first log:
http://pastebin.com/raw/EFzYR47x
with the latest:
http://pastebin.com/ApXqN4vx
you'll see that root path (/media/mihau/IPOD/) stays intact. The scripts does lowercase on everything after the root dir.

**Comment by NicoHood** [comment]
And what happens if you change the files manually to lowercase? Will it fix the problem? (I assume this is more a problem of the ID3 Tag).
Because I have a lot of music files with spaces, upper and lower case etc. I just cannot reproduce this, this is weird.

**Comment by mmalisz** [comment]
I've moved the VA folder to the root dir renamed the folder and files within to lowercase and it synced.
However, I got error on the end:
[+] Adding playlist /media/mihau/IPOD/va/va.pls
Error: Playlist does not contain a single track. Skipping playlist.

mihau@home:va$ cat va.pls 
fokuz podcast 20 - macca & kasper.mp3

**Comment by mmalisz** [comment]
So, the playlist error was my fault - forgot I should use m3u extension to just enter filenames.
Anyway, I get mutagen errors, but tracks are added anyway.

**Comment by mmalisz** [comment]
I've copied the file (name in lowecase) to the root and mutagen didn't give an error. I guess mutagen won't read the file if the original path and/or filename contains uppercase characters.

**Comment by NicoHood** [comment]
Hm but I do have files-folders with upper an lower case names.

Can zou please trz to add those music files:
http://kylegabler.com/WorldOfGooSoundtrack/

Those work for me, just to verify that it is not because of your special music files contain any errors.

**Comment by mmalisz** [comment]
Same result.
I've created the 'World Of Goo' folder in root directory, placed files there.
Also I've tried placing the files (with uppercases) directly in the root dir. No effect.

Maybe the mutagen version is the issue? I've got one installed from repo:
http://pastebin.com/f1XGHetj

**Comment by NicoHood** [comment]
which python version are you using?

I am running on elementary os (based on ubuntu 14.04), maybe this is the problem. I will try a debian vm later, but i think my ipod was not recognized there.

**Comment by mmalisz** [comment]
Python 2.7.9

**Comment by NicoHood** [comment]
Ubuntu 14.04 has 2.7.6
I do not know if this is the problem. I will try different OS.

**Comment by NicoHood** [comment]
I could reproduce this error with debian8.
I do not know if it is the python or mutagen version.

```
$ apt-cache show python-mutagen
Package: python-mutagen
Priority: optional
Section: python
Installed-Size: 406
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Tristan Seligmann <mithrandi@debian.org>
Architecture: all
Source: mutagen
Version: 1.22-1ubuntu2
```

**Comment by mmalisz** [comment]
I installed mutagen from source, so I guess this might be a debian-specific python bug.

**Comment by NicoHood** [comment]
I think its not a bug. I just checked which path with pass to the mutagen function call. And it is lower case. And this is effectively wrong. I think FAT does not essentially care about upper and lower case, but the filenames can still have upper and lower formats. However I've run the script in a local ext4 folder, so the error is expected. Did you run it on the FAT formatted ipod?

I guess we have to fix the whole script and remove this lower case thing on all functions. This is also what drove me crazy when adding the autoplaylist function. You have to keep the path TO the ipod in up/lower case and the rest in lower. I do not know why this design was used, but its suboptimal.

The filename is currently used for indexing the tracks (accessing them). Maybe if we have a problem with upper cases (i dont know yet), we could use a shasum (or md5) instead. This would be a good identifier still. And the ipod can handle upper case. However i was always wondering why the script does this lower case thing. Maybe @nims11 can answer this.

I try to patch this.

**Comment by mmalisz** [comment]
My iPod is FAT formatted. On branch autoplaylist there's a comment that says:
"Reformat fullPath so that the basepath is lower/upper and the rest lower.
This is required to get the correct position (track index) inside Playlist.construct()"

**Comment by NicoHood** [comment]
Yes I wrote this comment. This is because the script use(d) this format for accessing the array. I do not know why this decision was made.

I tried a quick fix on my branch, please test. **unicode function needs also an update.** I do not know what those functions do as nothing is commented and i never used them. Maybe @nims11 can have a look?

@mmalisz If it works, please test as many options that you have. All kind of filename, all kind of playlists and also try the new autoplaylist feature (add --a). Also test voiceover en and disabled.

**Comment by mmalisz** [comment]
So, autoplaylist works as expected (I guess).
However, when the folder contains playlist within (I've got an m3u file), then we're back to square one (the paths within iPod root are lowercase).
Both voiceover modes seem to work.

One thing about autoplaylist -- if the folder is named_like_this, the voiceover reads this as 'named underscore...' - you get the idea.

**Comment by NicoHood** [comment]
Hm_not_sure_if_you_should_name_your_folders_like_this or if we just should fix this with a search&replace. Good point.

m3u playlist code does not contain any lower() function. So I guess the m3u file contains wrong paths? Maybe because of this this general lower() function was used, i do not know.

Can you post an entry of the m3u file and the real filepath (with upper/lower)?

**Comment by mmalisz** [comment]
Real path: http://pastebin.com/KdThjBeK
Here are the paths from the error: http://pastebin.com/uvkX1Ceu

**Comment by NicoHood** [comment]
.pls is fixed. Please try and redownload the branch. Possibly m3u is also fixed with this, as the function is used in both playlist types.

**Comment by mmalisz** [comment]
m3u seems to be fixed.
One more thing:
You have to set the depth parameter if you call the argument before path:
shuffle.py: error: argument --auto-playlists: invalid int value: '/media/mihau/IPOD/'
However, the help prompt says that the deault value is set to -1 (no limit).
It works as expected if the --a argument is called after the path.

**Comment by NicoHood** [comment]
That is expected. You also cannot call the --disable function before path.

**Comment by mmalisz** [comment]
I wasn't aware of that :)
Closing this issue.

**Comment by nims11** [comment]
@NicoHood The lower case thing was already there when I forked the code. Although it is supposed to be harmless since FAT isn't case sensitive, it is breaking things with absolute paths in playlists. However, it is still justified to use `.lower()` at some places (https://github.com/nims11/IPod-Shuffle-4g/pull/29/commits/4134e93cd3c56680a893140bcd24898781bfb467#r58783240)
